### ISSUE TITLE
Version 1.2.4 is broken

### ISSUE THREAD

**Issue by stryaponoff** [khorark/mobx-flipper#16]
I've updated to mobx-flipper@1.2.4 and it doesn't contain the dist directory at all. Downgraded to 1.2.3 - everything is fine.

**Comment by khorark** [comment]
Hi! Thank you for your message. Yes, I see. I fixed it in version [1.2.5.](https://github.com/khorark/mobx-flipper/releases/tag/1.2.5). Please update and check.
