### ISSUE TITLE
not woking

### ISSUE THREAD

**Issue by medelvann** [khorark/mobx-flipper#2]
i have multi store like these codes 
       spy(createMobxDebugger(register));
          spy(createMobxDebugger(changeUserName));
          spy(createMobxDebugger(changeUserPassword));

but 
not changes in flipper and also every store has same state tree and not show diffs

**Comment by khorark** [comment]
I have not tested the functionality if there are multiple stores. Maybe I will add this functionality in future or you can create PR with this functionality.
